Support Android 8.0

diff --git a/tools/update-binary b/tools/update-binary
--- a/tools/update-binary
+++ b/tools/update-binary
@@ -2,6 +2,7 @@
 
 ver=
 tmp=/tmp/mipay-apps
+default_prop=/system/build.prop
 
 if [ "$3" ]; then
     zip=$3
@@ -28,7 +29,7 @@ abort() {
         print "Aborting..."
     }
     cleanup
-    print "Failed to install brevent!"
+    print "Failed to install mipay addons!"
     exit 1
 }
 
@@ -48,6 +49,14 @@ setperm() {
     find "$3" -type f -exec chmod "$2" {} \;
 }
 
+setprop() {
+    if grep -q "^[[:space:]]*$1[[:space:]]*=" "$default_prop"; then
+        sed -i "s/^[[:space:]]*$1[[:space:]]*=.*$/$1=$2/g" "$default_prop"
+    else
+        echo "$1=$2" >> "$default_prop"
+    fi
+}
+
 print "****************************"
 print "* MIUI 9 (EU) MiPay Addons *"
 print "****************************"
@@ -55,6 +64,10 @@ print "version: $ver"
 
 print "Mounting filesystems..."
 mount /system
+if mount | grep ro | grep -q /system; then
+    mount -o remount,rw /system || print "Failed to mount read-write!"
+    print 'Remount as read-write...'
+fi
 
 [ "$zip" ] && {
     extract "$zip" "$tmp"
@@ -79,6 +92,9 @@ for f in $app_list; do
     setperm 0755 0644 $f
 done
 #do_symlink
+
+print "Fixing build.prop for MiPay..."
+setprop "ro.se.type" "eSE,HCE,UICC" || abort "Failed to patch build.prop"
 
 umount /system
 cleanup
diff --git a/tools/update-binary-cleaner b/tools/update-binary-cleaner
--- a/tools/update-binary-cleaner
+++ b/tools/update-binary-cleaner
@@ -28,7 +28,7 @@ abort() {
         print "Aborting..."
     }
     cleanup
-    print "Failed to install brevent!"
+    print "Failed to install xiaomi.eu rom fix!"
     exit 1
 }
 
@@ -48,6 +48,16 @@ setperm() {
     find "$3" -type f -exec chmod "$2" {} \;
 }
 
+try_del() {
+    app=/system/$1
+    if [ -d $app ]; then
+        print "Removing ${app}..."
+        rm -r "$app" || print "failed to remove $app"
+    else
+        print "Skipping ${app}"
+    fi
+}
+
 print "***************************"
 print "* MIUI 9 (EU) Cleaner Fix *"
 print "***************************"
@@ -55,6 +65,10 @@ print "version: $ver"
 
 print "Mounting filesystems..."
 mount /system
+if mount | grep ro | grep -q /system; then
+    mount -o remount,rw /system || print "Failed to mount read-write!"
+    print 'Remount as read-write...'
+fi
 
 [ "$zip" ] && {
     extract "$zip" "$tmp"
@@ -70,13 +84,16 @@ print "Clean files..."
 rm -rf $app_list
 
 print "Adding files..."
-cp -R ./system/priv-app/* /system/priv-app/ || abort "Failed copy apps"
+cp -R ./system/priv-app/* /system/priv-app/ || abort "Failed to copy apps"
 
 print "Setting correct permissions..."
 for f in $app_list; do
     print "Fixing permission: $f"
     setperm 0755 0644 $f
 done
+
+print "Removing evil apps..."
+try_del app/MiuiDaemon
 
 umount /system
 cleanup
